// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// doColorRamp
StringVector doColorRamp(NumericMatrix colors, NumericVector x, bool alpha, std::string naColor);
RcppExport SEXP _scales_doColorRamp(SEXP colorsSEXP, SEXP xSEXP, SEXP alphaSEXP, SEXP naColorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type colors(colorsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< std::string >::type naColor(naColorSEXP);
    rcpp_result_gen = Rcpp::wrap(doColorRamp(colors, x, alpha, naColor));
    return rcpp_result_gen;
END_RCPP
}
// rgbToLab
NumericVector rgbToLab(NumericVector rgb);
RcppExport SEXP _scales_rgbToLab(SEXP rgbSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type rgb(rgbSEXP);
    rcpp_result_gen = Rcpp::wrap(rgbToLab(rgb));
    return rcpp_result_gen;
END_RCPP
}
// rgbToXyz
NumericVector rgbToXyz(NumericVector rgb);
RcppExport SEXP _scales_rgbToXyz(SEXP rgbSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type rgb(rgbSEXP);
    rcpp_result_gen = Rcpp::wrap(rgbToXyz(rgb));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_scales_doColorRamp", (DL_FUNC) &_scales_doColorRamp, 4},
    {"_scales_rgbToLab", (DL_FUNC) &_scales_rgbToLab, 1},
    {"_scales_rgbToXyz", (DL_FUNC) &_scales_rgbToXyz, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_scales(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
