# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

doColorRamp <- function(colors, x, alpha, naColor) {
    .Call('_scales_doColorRamp', PACKAGE = 'scales', colors, x, alpha, naColor)
}

rgbToLab <- function(rgb) {
    .Call('_scales_rgbToLab', PACKAGE = 'scales', rgb)
}

rgbToXyz <- function(rgb) {
    .Call('_scales_rgbToXyz', PACKAGE = 'scales', rgb)
}

